<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bannerMsg_File is successfully downloaded</name>
   <tag></tag>
   <elementGuidId>96cc1945-3306-4db4-a296-0fcf2ee7af66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.feedback-message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feedbackMessageContainer']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed6e153b-1fa5-4a97-8e89-7c28b92350ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedback-message-text</value>
      <webElementGuid>6d9160c1-b182-479e-be44-d0425234199a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>File is successfully downloaded.</value>
      <webElementGuid>f3fe213e-9993-45d6-8a53-8d57ea6a860d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feedbackMessageContainer&quot;)/div[@class=&quot;feedback-message feedback-message-success feedback-message-autoclose&quot;]/div[@class=&quot;feedback-message-text&quot;]</value>
      <webElementGuid>07e9dd51-ef8b-4d71-a86f-248792d56922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedbackMessageContainer']/div/div</value>
      <webElementGuid>6e3728a8-0039-4f4d-b8a3-2d73632dfda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[4]</value>
      <webElementGuid>851790f3-e419-415c-9a5a-ea3cf8ee6695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/preceding::div[4]</value>
      <webElementGuid>c60355c6-e0cb-4708-b0c2-aa08a222e259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='File is successfully downloaded.']/parent::*</value>
      <webElementGuid>7e27d7aa-62a6-4ddd-851f-255587281ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>5c6492c8-08f5-4220-830e-465a2ba14563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'File is successfully downloaded.' or . = 'File is successfully downloaded.')]</value>
      <webElementGuid>40d5196b-0db5-4a3f-b340-bc718823bed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
