<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Code_input-search</name>
   <tag></tag>
   <elementGuidId>d6da5245-8d09-4486-9293-a91d3360a81e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Input_VendorCode2&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[1]/div/div/div/div/div[3]/form/div[1]/div/div[1]/span/input[count(. | //input[@class = 'form-control OSFillParent' and @type = 'search' and @placeholder = 'Enter Vendor Code' and @aria-required = 'false' and @aria-describedby = 'aria-describedby=&quot;Input_VendorCode2_DescribedBy&quot;' and @maxlength = '50' and @value id = 'Input_VendorCode2' and @style = 'user-select: auto;']) = count(//input[@class = 'form-control OSFillParent' and @type = 'search' and @placeholder = 'Enter Vendor Code' and @aria-required = 'false' and @aria-describedby = 'aria-describedby=&quot;Input_VendorCode2_DescribedBy&quot;' and @maxlength = '50' and @value id = 'Input_VendorCode2' and @style = 'user-select: auto;'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.input-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>916ea51d-c8d7-463a-8390-6b93d43a87fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e6972102-4680-4d08-b976-6b6cd0f99ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>e5ee55ea-9d59-400a-9fce-9ba2e875b12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Vendor Code</value>
      <webElementGuid>e6f0d1f9-abe4-43d2-9184-de430128638d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>73818406-c32c-4d47-8f01-645569b5f0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>aria-describedby=&quot;Input_VendorCode2_DescribedBy&quot;</value>
      <webElementGuid>31a82b0d-f954-4e92-8f4b-c58a1f0bd6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fd55c26c-a7f8-4472-9802-08835df2dff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value id</name>
      <type>Main</type>
      <value>Input_VendorCode2</value>
      <webElementGuid>88ab8257-08dd-45c3-860f-b5b94cc2956b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>user-select: auto;</value>
      <webElementGuid>5025b2fa-7975-45bd-b44e-975b603b7368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[1]/div/div/div/div/div[3]/form/div[1]/div/div[1]/span/input</value>
      <webElementGuid>21ca9f30-b40b-4c68-ba5e-8d23dc3c9469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-Column1']/span</value>
      <webElementGuid>fa6ff47b-470d-4c98-b8df-f119e0e1a20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Code'])[1]//span[1]</value>
      <webElementGuid>96c247e8-d279-4e73-b18f-be76f405b258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance Advice'])[3]/following::span[1]</value>
      <webElementGuid>80e1b4d6-2d79-4322-a20c-b803b65e125a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[1]/preceding::span[1]</value>
      <webElementGuid>1c81aa6e-6b9f-4e99-b0a3-3e7a84e35445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/span</value>
      <webElementGuid>7e44c585-089f-4fb2-a3a7-3ef20a902091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
