<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Code_input-search</name>
   <tag></tag>
   <elementGuidId>d6da5245-8d09-4486-9293-a91d3360a81e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.input-search</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[1]/div/div/div/div/div[3]/form/div[1]/div/div[1]/span/input[count(. | //input[@class = 'form-control OSFillParent' and @type = 'search' and @placeholder = 'Enter Vendor Code' and @aria-required = 'false' and @aria-describedby = 'aria-describedby=&quot;Input_VendorCode2_DescribedBy&quot;' and @maxlength = '50' and @value id = 'Input_VendorCode2' and @style = 'user-select: auto;']) = count(//input[@class = 'form-control OSFillParent' and @type = 'search' and @placeholder = 'Enter Vendor Code' and @aria-required = 'false' and @aria-describedby = 'aria-describedby=&quot;Input_VendorCode2_DescribedBy&quot;' and @maxlength = '50' and @value id = 'Input_VendorCode2' and @style = 'user-select: auto;'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[1]/div/div/div/div/div[3]/form/div[1]/div/div[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33d2cf3a-63f2-4295-818e-c694f0769f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>20a79bf1-5d26-49c2-ae4a-9dda60b2bddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>df2e1506-4d60-47d8-9800-7bd92f741e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Vendor Code</value>
      <webElementGuid>f119b813-c2f8-428c-a503-3678a5adda5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>770640fb-a4a8-4b1b-adb2-ae4c8a056806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>aria-describedby=&quot;Input_VendorCode2_DescribedBy&quot;</value>
      <webElementGuid>4ab9d366-d8e7-4638-9a4b-97c3b4af0127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>04aa7d44-6378-48ad-82c7-fcf297f813e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value id</name>
      <type>Main</type>
      <value>Input_VendorCode2</value>
      <webElementGuid>2fd30d0e-7c4c-4167-be6d-98558c26afd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>user-select: auto;</value>
      <webElementGuid>cc0b9385-3583-47f9-a9e9-30057c412e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[1]/div/div/div/div/div[3]/form/div[1]/div/div[1]/span/input</value>
      <webElementGuid>84609825-acd0-4906-b8c6-8e893fdf9bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-Column1']/span</value>
      <webElementGuid>98126d33-2935-4336-b472-f4e5a8b7a52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Code'])[1]//span[1]</value>
      <webElementGuid>948bb1f4-8790-4028-957a-376b1a5f0507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance Advice'])[3]/following::span[1]</value>
      <webElementGuid>005a7c75-c8fc-49e4-bca8-ed9469b295e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[1]/preceding::span[1]</value>
      <webElementGuid>aa885857-9a7a-4427-8270-d4e049fa5ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/span</value>
      <webElementGuid>f280e30d-13cf-4116-ae1e-19bae287a09f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
