<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Payment Voucher Number</name>
   <tag></tag>
   <elementGuidId>ed364847-fc63-4514-b752-969c6cd96959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b13-Column1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b13-Column1&quot;)[count(. | //div[@class = 'columns-item' and @id = 'b13-Column1' and (text() = 'Payment Voucher Number' or . = 'Payment Voucher Number')]) = count(//div[@class = 'columns-item' and @id = 'b13-Column1' and (text() = 'Payment Voucher Number' or . = 'Payment Voucher Number')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b13-Column1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>398f931d-b13a-4a96-9082-9fe7db50e889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>6c9f058f-1c5b-4c9f-86e6-c3ee6ac59d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b13-Column1</value>
      <webElementGuid>ee38dfa6-8571-4ad5-ba4b-bbd39e19bd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Voucher Number</value>
      <webElementGuid>be422403-b11b-4aa0-b3ad-45cf1bb155b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b13-Column1&quot;)</value>
      <webElementGuid>c92b2686-5947-43e6-bb0f-fc6c0ee7939d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b13-Column1']</value>
      <webElementGuid>dc5a078f-a5ed-422f-b2fa-d8d52e77a802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b13']/div/div</value>
      <webElementGuid>1cc4d9d7-ccbc-4b35-bf98-257b08ecfebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + up/down arrow keys to navigate through years;'])[2]/following::div[3]</value>
      <webElementGuid>0367a2bb-924b-40ae-906a-cae3cc413f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + right/left arrow keys to navigate through months;'])[2]/following::div[3]</value>
      <webElementGuid>30f0f512-7078-4b58-841b-5d829dec9795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RA Number'])[1]/preceding::div[1]</value>
      <webElementGuid>9eb52f78-bdd4-4a3a-a93a-fe342c6738f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Voucher Number']/parent::*</value>
      <webElementGuid>d636c09b-884f-4b65-b202-1f8734cd6dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>9ee223be-efa3-4725-bf75-b8c6459437ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b13-Column1' and (text() = 'Payment Voucher Number' or . = 'Payment Voucher Number')]</value>
      <webElementGuid>b4ee8445-a0ea-4af2-8cfc-5db5c88c1dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
