<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RA Number</name>
   <tag></tag>
   <elementGuidId>a4741ac9-9fb6-49a6-b059-05745832c209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-Column1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;b13-Column2&quot;][count(. | //div[@class = 'columns-item' and @id = 'b13-Column2' and (text() = 'RA Number' or . = 'RA Number')]) = count(//div[@class = 'columns-item' and @id = 'b13-Column2' and (text() = 'RA Number' or . = 'RA Number')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-Column1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57ed9ee2-7773-41b9-bc59-c63fb4aa84db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>ccbcfae0-386c-437e-8a9e-6b6aef9c7075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b13-Column2</value>
      <webElementGuid>7272d2fa-b8ad-4b45-a3bf-05bcec7248ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RA Number</value>
      <webElementGuid>f51fe152-3ad8-4e2b-ab47-4187765c422a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;b13-Column2&quot;]</value>
      <webElementGuid>2d42fd70-13eb-4024-b975-ec4dc1e0fb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-Column1']</value>
      <webElementGuid>17383843-8027-411d-9969-15e9a929e43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b3']/div/div</value>
      <webElementGuid>e1d1ab2d-a1cb-498c-bade-88013123d08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance Advice'])[3]/following::div[5]</value>
      <webElementGuid>133eea73-d32d-46cf-a332-180dee987d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[11]</value>
      <webElementGuid>1435bb0d-32bb-4dcc-a5da-0f576df1bbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[1]/preceding::div[1]</value>
      <webElementGuid>337405e9-6e3f-4151-9f8e-18cba12d8aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vendor Code']/parent::*</value>
      <webElementGuid>a84b8ec4-518f-408f-a6d2-47b4872bf839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>3da7c216-54eb-4a07-a8f1-b49e57f0508d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-Column1' and (text() = 'Vendor Code' or . = 'Vendor Code')]</value>
      <webElementGuid>77b1f0e5-c0ef-4247-8362-b1904da24699</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
