<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Payment Date To</name>
   <tag></tag>
   <elementGuidId>1a31858c-4bff-4aa6-a4bf-536765841519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-Column4']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b3-Column4&quot;)[count(. | //div[@class = 'columns-item' and @id = 'b3-Column4' and (text() = 'Payment Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;' or . = 'Payment Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;')]) = count(//div[@class = 'columns-item' and @id = 'b3-Column4' and (text() = 'Payment Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;' or . = 'Payment Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-Column4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>137d1718-a07e-4889-af32-6b69f36cc5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>63b14315-5cc4-40bb-a293-fcb63e50b144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-Column4</value>
      <webElementGuid>1d7bac6e-c863-4e44-880d-a0dfac169d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Date To</value>
      <webElementGuid>b999531c-0cc1-45a2-9273-028fa7d225af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-Column4&quot;)</value>
      <webElementGuid>53761911-c8f8-444f-a153-4f4bd73e280a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-Column4']</value>
      <webElementGuid>d1dfd6d6-03a0-41bf-a766-748d7bfde3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b3']/div/div[4]</value>
      <webElementGuid>7479507c-0c66-4096-bc50-0c61c4cfcccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + up/down arrow keys to navigate through years;'])[1]/following::div[1]</value>
      <webElementGuid>f1ba7e43-b2c5-49bd-bdab-be894551fe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + right/left arrow keys to navigate through months;'])[1]/following::div[1]</value>
      <webElementGuid>04e596ca-2a07-4eda-a3c8-bebcaa16fb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Date To']/parent::*</value>
      <webElementGuid>13665069-3411-4c78-9011-b9a6ea66e360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]</value>
      <webElementGuid>da9ff30d-161b-4730-a1a2-e013adc7e70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-Column4' and (text() = 'Payment Date To')]</value>
      <webElementGuid>afff3576-8a6d-4d46-84f1-2830064918cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
