<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Vendor Name</name>
   <tag></tag>
   <elementGuidId>084b4999-ef44-47f1-ac46-02d0abc4c736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Code'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b3-Column2&quot;)[count(. | //div[@class = 'columns-item' and @id = 'b3-Column2' and (text() = 'Vendor Name' or . = 'Vendor Name')]) = count(//div[@class = 'columns-item' and @id = 'b3-Column2' and (text() = 'Vendor Name' or . = 'Vendor Name')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-Column2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a05eef84-4414-4262-8de3-62cc35058a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>b305117a-5efc-4483-aad8-46f166f0078b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-Column2</value>
      <webElementGuid>ae558c29-d17b-412e-af67-2daff333447b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vendor Name</value>
      <webElementGuid>7fc1c71d-cae3-425c-89cc-2309b2fe2dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-Column2&quot;)</value>
      <webElementGuid>fd86af23-a997-48c1-98ae-244689858ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-Column2']</value>
      <webElementGuid>f544c9b0-f68f-4a20-8a30-788c891f8e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b3']/div/div[2]</value>
      <webElementGuid>71c09bbf-5f96-4d3b-85de-01fb0b972599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Code'])[1]/following::div[1]</value>
      <webElementGuid>3e07a10c-a0ff-4008-ae81-c170a8defc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance Advice'])[3]/following::div[6]</value>
      <webElementGuid>b4517d2d-1c61-4a0a-b7d9-bde3ba2718a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vendor Name']/parent::*</value>
      <webElementGuid>20e75df1-e72f-464a-b1d7-9ee2bdd9f7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]</value>
      <webElementGuid>a6b0398c-0700-49ea-91b9-afcfadaca0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-Column2' and (text() = 'Vendor Name' or . = 'Vendor Name')]</value>
      <webElementGuid>b9227500-ff0b-4754-9c58-82d0fd858926</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
