<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Payment Date From</name>
   <tag></tag>
   <elementGuidId>8d18ae54-cbba-4571-a655-fc187f37f44e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-Column3']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;b3-Column3&quot;]/text()[count(. | //div[@class = 'columns-item' and @id = 'b3-Column3' and (text() = 'Payment Date From' or . = 'Payment Date From')]) = count(//div[@class = 'columns-item' and @id = 'b3-Column3' and (text() = 'Payment Date From' or . = 'Payment Date From')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-Column3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62f8bc62-11c0-450d-a920-972a7c633e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>36525ae5-113f-493f-b280-6d4ebfdefe9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-Column3</value>
      <webElementGuid>76405277-1b8f-4b7b-ba61-44e60336b3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Date From</value>
      <webElementGuid>a2ad0d25-d083-45db-ac79-2c42b0c7493a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;b3-Column3&quot;]/text()</value>
      <webElementGuid>fa7e53ee-39cd-4a35-85c8-b8d86af96ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-Column3']</value>
      <webElementGuid>455cadf4-15e0-400e-8da5-0b3571a8c1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b3']/div/div[3]</value>
      <webElementGuid>0f845e6f-4d01-4ebd-b6d5-6d1eb663935f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[1]/following::div[1]</value>
      <webElementGuid>af1ed3c5-620a-4e59-9b4d-0356a22fba57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Code'])[1]/following::div[2]</value>
      <webElementGuid>294dba12-8e0f-42b7-be81-20e697c0d897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Date From']/parent::*</value>
      <webElementGuid>aaf004be-71d0-4bc6-9ac3-ef0cd2b122dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[3]</value>
      <webElementGuid>a673b7c6-b033-487b-bb90-5470f2833fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-Column3' and (text() = 'Payment Date From')]</value>
      <webElementGuid>1a0f597e-3283-4626-85af-939d0bbf0a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
