<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Watsons User Role  AccessUpdate Watsons_052fdb</name>
   <tag></tag>
   <elementGuidId>bedc68f8-9aaa-49e2-b9d5-b394ba115d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b1-MainContentWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContentWrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc2c11e7-d597-413e-9c77-5a11420e6189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-content padding-x-xl padding-y-xl</value>
      <webElementGuid>7ea52f55-9bd1-4424-a445-6f7b9a6fdb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>67741b4d-cdf1-4450-8e85-c603cbbadc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-MainContentWrapper</value>
      <webElementGuid>f9454233-0cb3-4f46-8b51-9f5256cade8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watsons User Role &amp; AccessUpdate Watsons's UserName, Email, Updated ByRoleSelect AllSuper AdminAdminAP UserTicket TypeSelect TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SAStatusSelect AllActiveInactiveCreated Date FromIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;Created Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;SearchResetRows per page 10Rows per page 50Rows per page 100NameEmailCreated DateTicket TypeRoleUpdated ByUpdate DateStatusActionJordan Domanaisjordan.domanais@dbresults.com.hk10/27/2023----InactiveAKO-AOM WATSONSayalathe30th@watsons.com.ph10/25/2023----InactiveAOM Branch A AOMsmgbrancha_AOM@test.com10/25/2023----InactiveSR IT Solomon Requestorit.solomonrequestor@gmail.com10/24/2023----InactiveMarky Test 2 Regaladomarcelo.regalado@dbresults.com.hk10/23/2023----InactiveMarky Regaladomarcelo.regalado@dbresults.com.ph10/23/2023----InactiveNikko Gonzalesaldrin.gonzales@dbresults.com.ph10/23/2023----InactiveMichelle Oberesmichelle.oberes@dbresults.com.ph10/23/2023----InactiveCapex SM ThirdApproversm.thirdapprover@gmail.com10/20/2023----InactiveCapex SM SecondApproversm.secondapprover@gmail.com10/20/2023----Inactive1 to 10 of 189 items1234...19</value>
      <webElementGuid>495989c7-0bd2-4bed-9898-2429e04ef4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-MainContentWrapper&quot;)</value>
      <webElementGuid>d3b0ef91-4aff-4ded-8acf-2a2a3ea9b366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContentWrapper']</value>
      <webElementGuid>f6987fb7-17b7-4d17-92d1-44b53c1459a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-Content']/div</value>
      <webElementGuid>60b275b0-9b52-413b-b9c8-71b1ff55ef26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[3]</value>
      <webElementGuid>89375a36-7b04-4743-bae7-7e3c19050f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobarak Dimalotang'])[1]/following::div[4]</value>
      <webElementGuid>bde714f3-5339-4a36-9f61-90feee98fb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>3fae68ae-5104-49ab-be89-c7d05fa69169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b1-MainContentWrapper' and (text() = concat(&quot;Watsons User Role &amp; AccessUpdate Watsons&quot; , &quot;'&quot; , &quot;s UserName, Email, Updated ByRoleSelect AllSuper AdminAdminAP UserTicket TypeSelect TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SAStatusSelect AllActiveInactiveCreated Date FromIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;Created Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;SearchResetRows per page 10Rows per page 50Rows per page 100NameEmailCreated DateTicket TypeRoleUpdated ByUpdate DateStatusActionJordan Domanaisjordan.domanais@dbresults.com.hk10/27/2023----InactiveAKO-AOM WATSONSayalathe30th@watsons.com.ph10/25/2023----InactiveAOM Branch A AOMsmgbrancha_AOM@test.com10/25/2023----InactiveSR IT Solomon Requestorit.solomonrequestor@gmail.com10/24/2023----InactiveMarky Test 2 Regaladomarcelo.regalado@dbresults.com.hk10/23/2023----InactiveMarky Regaladomarcelo.regalado@dbresults.com.ph10/23/2023----InactiveNikko Gonzalesaldrin.gonzales@dbresults.com.ph10/23/2023----InactiveMichelle Oberesmichelle.oberes@dbresults.com.ph10/23/2023----InactiveCapex SM ThirdApproversm.thirdapprover@gmail.com10/20/2023----InactiveCapex SM SecondApproversm.secondapprover@gmail.com10/20/2023----Inactive1 to 10 of 189 items1234...19&quot;) or . = concat(&quot;Watsons User Role &amp; AccessUpdate Watsons&quot; , &quot;'&quot; , &quot;s UserName, Email, Updated ByRoleSelect AllSuper AdminAdminAP UserTicket TypeSelect TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SAStatusSelect AllActiveInactiveCreated Date FromIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;Created Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;SearchResetRows per page 10Rows per page 50Rows per page 100NameEmailCreated DateTicket TypeRoleUpdated ByUpdate DateStatusActionJordan Domanaisjordan.domanais@dbresults.com.hk10/27/2023----InactiveAKO-AOM WATSONSayalathe30th@watsons.com.ph10/25/2023----InactiveAOM Branch A AOMsmgbrancha_AOM@test.com10/25/2023----InactiveSR IT Solomon Requestorit.solomonrequestor@gmail.com10/24/2023----InactiveMarky Test 2 Regaladomarcelo.regalado@dbresults.com.hk10/23/2023----InactiveMarky Regaladomarcelo.regalado@dbresults.com.ph10/23/2023----InactiveNikko Gonzalesaldrin.gonzales@dbresults.com.ph10/23/2023----InactiveMichelle Oberesmichelle.oberes@dbresults.com.ph10/23/2023----InactiveCapex SM ThirdApproversm.thirdapprover@gmail.com10/20/2023----InactiveCapex SM SecondApproversm.secondapprover@gmail.com10/20/2023----Inactive1 to 10 of 189 items1234...19&quot;))]</value>
      <webElementGuid>6c8bbd91-c55f-4469-99cb-a42128cb4a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
