<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Select Role</name>
   <tag></tag>
   <elementGuidId>4371017e-8586-417f-b0cc-ebd259e0ae70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='columns-item' and @id='b2-Column2']/text()[normalize-space()]
[count(. | //div[@class = 'columns-item' and @id = 'b2-Column2']) = count(//div[@class = 'columns-item' and @id = 'b2-Column2'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-Column2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-Column2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9fd4209c-0a3a-4775-92bf-3c0231c374b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>e31f4b14-c1a4-47a9-b2b1-506e42e1fc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-Column2</value>
      <webElementGuid>bab37cea-f274-4658-bd15-48c89240a12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='columns-item' and @id='b2-Column2']/text()[normalize-space()]
</value>
      <webElementGuid>31c52a73-7fc8-4d4d-9520-5b5745dfac1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-Column2']</value>
      <webElementGuid>b780bbca-0ca3-49ac-87c2-651fd4946641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b2']/div/div[2]</value>
      <webElementGuid>80a95d11-048e-44dc-9edf-cdb62ae485a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name, Email, Updated By'])[1]/following::div[1]</value>
      <webElementGuid>cc0aa87e-a40d-4ba3-b992-867bc4d28556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Update Watsons', &quot;'&quot;, 's User')])[1]/following::div[5]</value>
      <webElementGuid>864379e5-f0c9-4f03-a029-4d2d9221ebb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Role']/parent::*</value>
      <webElementGuid>e7e82895-ff30-46df-bd78-542235a1f3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]</value>
      <webElementGuid>ca650584-9c45-4811-b8c0-1d3e6959e5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-Column2' and (contains(text(),'Role'))]</value>
      <webElementGuid>249c2a11-ce41-4764-a58a-545049911328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
