<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Created Date From</name>
   <tag></tag>
   <elementGuidId>6280a90a-a25d-4262-b27b-104e43e50e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-Column1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-Column1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c35e3da1-bb87-4f8b-8f35-4f98e60002f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>51598abe-c353-41c4-8179-532647adbbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-Column1</value>
      <webElementGuid>b84a62a8-5ee5-4586-b2b4-805859d61712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Created Date FromIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;</value>
      <webElementGuid>4f3125aa-c889-4c03-a181-5510713c22f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-Column1&quot;)</value>
      <webElementGuid>b04873f1-a386-46dc-a66b-fc73cb84fe06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-Column1']</value>
      <webElementGuid>96bbd908-7780-46fb-bd90-0ed303cbc276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b3']/div/div</value>
      <webElementGuid>890dc8ad-78f0-4bd5-b01f-31b61741a351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Created Date From']/parent::*</value>
      <webElementGuid>125d9e88-e406-4d79-8588-2096a8cb51a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>3e03a3d6-61d2-432f-a8af-c7a773ecdfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-Column1' and (text() = 'Created Date FromIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;' or . = 'Created Date FromIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;')]</value>
      <webElementGuid>28d6b589-1102-468e-9696-1dfa1321775a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
