<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Ticket Type</name>
   <tag></tag>
   <elementGuidId>dcdf8c11-7aee-49c3-ae37-3125224ee7a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-Column3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-Column3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbef1068-72c4-445e-9546-ded31c26286c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>fd6361f5-3f0b-4249-a38f-3fd4e06ff5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-Column3</value>
      <webElementGuid>80aa66e1-a11d-4af7-95ba-18efbebb521d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ticket TypeSelect TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SA</value>
      <webElementGuid>de86e052-4e66-41d4-87ac-8057b3ced0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-Column3&quot;)</value>
      <webElementGuid>4180c0ea-5f17-44e1-8a39-c136ae5d20cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-Column3']</value>
      <webElementGuid>9e3f8723-23cc-43ae-b528-c34ebe5e3e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b2']/div/div[3]</value>
      <webElementGuid>4ceffc45-74aa-4636-b5af-28f9ce651c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name, Email, Updated By'])[1]/following::div[3]</value>
      <webElementGuid>1faba9ee-72f6-49d1-a89d-ec658ba13483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[3]</value>
      <webElementGuid>c853674a-f4d8-48b2-82ab-8430bc76c237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-Column3' and (text() = 'Ticket TypeSelect TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SA' or . = 'Ticket TypeSelect TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SA')]</value>
      <webElementGuid>470a657d-9b5e-4558-b462-b1d45583960c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
