<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Name, Email, Updated By</name>
   <tag></tag>
   <elementGuidId>6549eca6-1efd-4d60-a2f1-a0a2e3a58131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-Column1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-Column1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c3c8034-6f46-4522-a5cf-6536048c5aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>fb88f326-92c1-42b2-a39c-583be88e534f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-Column1</value>
      <webElementGuid>6cdb7cd4-b188-437e-bc7e-617939a7108f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name, Email, Updated By</value>
      <webElementGuid>44ab2f72-a0f0-45cf-8e98-d2207e8a05ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-Column1&quot;)</value>
      <webElementGuid>f6abf802-343a-4df0-af82-0fcdb4df41fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-Column1']</value>
      <webElementGuid>65173c33-ba35-47b3-bb44-6afb66ce186c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b2']/div/div</value>
      <webElementGuid>7b14440f-e1ef-497f-aeb4-3969e274e840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Update Watsons', &quot;'&quot;, 's User')])[1]/following::div[4]</value>
      <webElementGuid>b9bac6d3-c114-4d44-a2a8-7d5751cd667f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watsons User Role &amp; Access'])[1]/following::div[7]</value>
      <webElementGuid>8b0929fe-73bf-4a88-ae5f-3a6de89f5759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name, Email, Updated By']/parent::*</value>
      <webElementGuid>8b4eea05-4c5e-4d46-a0b8-a50bd935e0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>2dd1542d-0c25-4738-a6be-4082db8c7337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-Column1' and (text() = 'Name, Email, Updated By' or . = 'Name, Email, Updated By')]</value>
      <webElementGuid>d93c6f6d-5fc7-43a0-9d90-e8f1cd589e22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
