<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Created Date To</name>
   <tag></tag>
   <elementGuidId>fc2b08d2-d24f-4858-bd3f-139fa16c316c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-Column2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-Column2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d08c919-162e-4d4f-8d31-df1e3bc11b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>4782dca5-3cf0-4b1c-9412-1a1d6568ee14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-Column2</value>
      <webElementGuid>1f8eba32-d1aa-4be5-adae-0fbbeba1c031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Created Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;</value>
      <webElementGuid>59cc6da1-4494-40d0-92c2-47a333a4b08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-Column2&quot;)</value>
      <webElementGuid>404500fc-0fa0-4cb5-b4e0-0f63a922804e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-Column2']</value>
      <webElementGuid>3bbe8631-ad73-4665-b807-56a76c368e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b3']/div/div[2]</value>
      <webElementGuid>cff97943-67db-47ca-a95a-230cfd3e484e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + up/down arrow keys to navigate through years;'])[1]/following::div[1]</value>
      <webElementGuid>3f1793d1-389d-487f-928e-7bb05ef9044f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + right/left arrow keys to navigate through months;'])[1]/following::div[1]</value>
      <webElementGuid>85ad3536-b2cf-4dbe-877e-89444e5f4389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Created Date To']/parent::*</value>
      <webElementGuid>52b9761e-8cd0-4c76-bd9a-99f0a3e74e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>1bf972f2-9ef5-459f-80db-db891331b7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-Column2' and (text() = 'Created Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;' or . = 'Created Date ToIn order to be able to navigate through calendar with keyboard key:Use cmd or ctrl + down arrow key to navigate into calendar context;Use arrow keys to navigate through calendar days;Use cmd or ctrl + right/left arrow keys to navigate through months;Use cmd or ctrl + up/down arrow keys to navigate through years;')]</value>
      <webElementGuid>4eda990c-3cfb-492f-8100-ba04e331f0a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
