<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selection_TicketType</name>
   <tag></tag>
   <elementGuidId>5cf7816d-6476-41a2-8d07-78d54351796f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown_Type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown_Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6e3f975-75f1-4106-8df4-31dcdb35c705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>117009c2-6d02-436a-b14f-6b690076e85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a608fbc-f196-40af-b2cb-47ec645d61d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown_Type</value>
      <webElementGuid>2349e58d-2b36-4b5b-a189-aa3a2214c134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SA</value>
      <webElementGuid>24ccd9e5-14f8-41d3-a739-9d3dbe66835e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown_Type&quot;)</value>
      <webElementGuid>d727ff4e-6302-4788-95fb-14d5efc44904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown_Type']</value>
      <webElementGuid>bbae5748-c906-49de-9b7c-003dff628f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown_Type-container']/select</value>
      <webElementGuid>9cd9bbf9-ef59-43b6-be07-9a99352edf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>4546c0db-54c3-4ea2-9c1c-1a40d2ea71d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown_Type' and (text() = 'Select TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SA' or . = 'Select TypePayment Follow up2307 Follow upBulletin Memo Follow UpAccount Follow UpRA Follow UpEarly - Discount TicketsAlternating CurrentDirect CurrentParking TicketTicket 1 specialist 1 SA')]</value>
      <webElementGuid>569a73ed-aa53-467b-8739-9eedfb08188c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
