<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TicketType</name>
   <tag></tag>
   <elementGuidId>6efdd88f-9768-4d57-afcf-ebdf8190630b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-angle-right.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b11-b1-DropdownBarArrow']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1a12ca51-dd52-4a69-8d44-b5a634231eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-angle-right fa-2x</value>
      <webElementGuid>7d51250a-e0b8-482e-8864-0bb2f246a4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b11-b1-DropdownBarArrow&quot;)/i[@class=&quot;icon fa fa-angle-right fa-2x&quot;]</value>
      <webElementGuid>c6c34089-17ab-40b0-af38-968d5ea5d221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b11-b1-DropdownBarArrow']/i</value>
      <webElementGuid>da9e72ea-9290-4135-9d76-9d976edaf2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/i</value>
      <webElementGuid>c1ff5dad-6dd6-4964-ac32-1f3278754fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
