<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selection_Rows per page</name>
   <tag></tag>
   <elementGuidId>db821d62-ae9d-4ca4-be06-9d547bb86545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown_RowPerPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown_RowPerPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af87f015-7526-4547-bef2-7dc307ca32e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>95326908-b1f1-459b-9081-34a418f5c5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>371c489d-55e7-4626-bda4-9f31c5745594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown_RowPerPage</value>
      <webElementGuid>4af5a95d-5c9d-410f-97ff-eed5f3d0ef50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rows per page 10Rows per page 50Rows per page 100</value>
      <webElementGuid>63bf994e-600c-4011-8875-f24377484826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown_RowPerPage&quot;)</value>
      <webElementGuid>ea62ac3c-ee68-4694-b02a-80763586591a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown_RowPerPage']</value>
      <webElementGuid>d0fd1f6b-4bc3-4a1e-9eb2-1c28334dff1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown_RowPerPage-container']/select</value>
      <webElementGuid>084c849d-66f4-48cd-9895-ebb0173b74ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::select[1]</value>
      <webElementGuid>88bf1cb1-5dfa-40b7-8f76-b1d4100df0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::select[1]</value>
      <webElementGuid>20831c7f-586d-4885-b9c6-1a2e4336838d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::select[1]</value>
      <webElementGuid>94a616c0-583a-4421-9e74-0459fabdc884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::select[1]</value>
      <webElementGuid>94bc310a-71f3-47ea-b0e9-45dcd7ff587b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/select</value>
      <webElementGuid>2935ef82-c378-47af-8929-3773cb0c83ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown_RowPerPage' and (text() = 'Rows per page 10Rows per page 50Rows per page 100' or . = 'Rows per page 10Rows per page 50Rows per page 100')]</value>
      <webElementGuid>06077a4f-1676-40bf-a7f5-c98159c91d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
