<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selection_Status</name>
   <tag></tag>
   <elementGuidId>5b603919-ddae-4bd0-8ebd-5c88f09d4b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown_Status2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown_Status2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>563dec55-55ef-46f7-b8f1-9d229d4f7afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>eb8b4534-efb5-4dcd-add2-0e3db39b8c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b15f37b-9ec9-4dc9-9124-d5b204cf8027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown_Status2</value>
      <webElementGuid>5cfb48cc-70a2-47d4-8f05-02943f1960d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select AllActiveInactive</value>
      <webElementGuid>d46f3efd-ad3d-414c-9f94-267b77fb5ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown_Status2&quot;)</value>
      <webElementGuid>febb405d-f425-482e-ae6f-7ee03225446f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown_Status2']</value>
      <webElementGuid>589b158f-c47c-420b-bfc3-aa442b774fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown_Status2-container']/select</value>
      <webElementGuid>bdbf669e-83eb-4a91-a1b2-6730afa76447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>70135a44-345b-49f4-8d4e-6fefd2f35b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown_Status2' and (text() = 'Select AllActiveInactive' or . = 'Select AllActiveInactive')]</value>
      <webElementGuid>6010fdf1-fa94-410e-a63f-03be7f39c795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
