<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selection_SelectRole</name>
   <tag></tag>
   <elementGuidId>fb85d13f-3785-4423-a363-f17452be3eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown_Role</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown_Role']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>37339c14-d70f-4177-a638-3176cde7c6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>99a0a5c1-9944-43e2-a9f8-61a289ecbae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>883a9748-f886-4deb-8b1d-d75117da2029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown_Role</value>
      <webElementGuid>365b66fe-31c4-4039-81d5-34942c563b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select AllSuper AdminAdminAP User</value>
      <webElementGuid>6d8cd398-2e01-4aea-9862-48652eef2873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown_Role&quot;)</value>
      <webElementGuid>0e3a3d06-9c66-4868-aba6-f18dfd88419a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown_Role']</value>
      <webElementGuid>1ec37f5b-fc5b-4d77-930e-7a9bd6874cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown_Role-container']/select</value>
      <webElementGuid>894f4740-a3f1-4654-a2ea-8f3f34aa9375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name, Email, Updated By'])[1]/following::select[1]</value>
      <webElementGuid>e467b85d-d949-4131-9de6-05cab76ebb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>44c42390-240e-4974-9524-b371c01c2728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown_Role' and (text() = 'Select AllSuper AdminAdminAP User' or . = 'Select AllSuper AdminAdminAP User')]</value>
      <webElementGuid>cdf36cc4-226e-4bad-a864-f8fe44fd9ee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
