<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Role</name>
   <tag></tag>
   <elementGuidId>42b0311f-709d-43cf-ba95-6df35e9bec9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b11-Dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b11-Dropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>55237e05-c850-4059-bd30-3b2d6d5dca85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>73fa07b4-7d9b-46af-8b01-7cca1b433dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea6fd971-b808-4590-b719-07bc06418ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b11-Dropdown</value>
      <webElementGuid>5695b341-3182-43c6-adc8-c7ab06d00d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select RoleSuper AdminAdminAP User</value>
      <webElementGuid>b1ece79d-5622-4253-b0e8-67a70aed8f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b11-Dropdown&quot;)</value>
      <webElementGuid>69b383dd-9d15-4464-aebb-eb2dd2637a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b11-Dropdown']</value>
      <webElementGuid>dab0e3fb-22bb-4b79-b418-6ea5bbea27e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b11-Dropdown-container']/select</value>
      <webElementGuid>657dd804-71cf-4a85-b330-5afb1b9c7bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[2]/following::select[1]</value>
      <webElementGuid>33bfe116-33ff-4243-967a-2d39b8422179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::select[1]</value>
      <webElementGuid>17812899-e0ad-4b98-9f76-c538fa653a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Type'])[3]/preceding::select[1]</value>
      <webElementGuid>8e02e5fd-96a6-4654-bd5c-1813160727c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select From List'])[1]/preceding::select[1]</value>
      <webElementGuid>9931afc0-d71c-4715-904f-6c0d902a67f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/select</value>
      <webElementGuid>0d1f6837-acbc-4610-af05-8f3e912f8ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b11-Dropdown' and (text() = 'Select RoleSuper AdminAdminAP User' or . = 'Select RoleSuper AdminAdminAP User')]</value>
      <webElementGuid>a7dbc713-aeec-458c-86a2-f8976ce622c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
