<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titlePage_Watsons User Role  Access</name>
   <tag></tag>
   <elementGuidId>ea0d8884-9ba4-4f11-86ad-cabf4cde0b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Screen_Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='Screen_Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f8c81982-c82f-48e0-8331-16788d9364e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Screen_Title</value>
      <webElementGuid>3d6991c0-9249-44c0-9241-5973d6a6eec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watson's User Role &amp; Access</value>
      <webElementGuid>a2ad27e5-040c-4c8d-8f31-7b796428ed5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Screen_Title&quot;)</value>
      <webElementGuid>5dd77b2a-d3ae-458a-a1c8-56c5a3857805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='Screen_Title']</value>
      <webElementGuid>5ab1e4c0-f543-47cb-84cd-8d1db1d40424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-Title']/h1</value>
      <webElementGuid>4495150c-3bbd-4122-a01f-dcebea0aa5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::h1[1]</value>
      <webElementGuid>a53aaf52-aed0-4f3d-bd9f-0423eb9d4cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobarak Dimalotang'])[1]/following::h1[1]</value>
      <webElementGuid>c45cee0e-3558-4b2b-a40c-ab4b065d9c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Watsons'])[1]/preceding::h1[1]</value>
      <webElementGuid>6436966f-188f-42a7-a609-72abfaef8f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Template'])[1]/preceding::h1[1]</value>
      <webElementGuid>841c7935-60f2-4eb9-81ef-b9d0f897b7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>bce8a855-8bcb-4fb0-8d0c-755bd2980f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'Screen_Title' and (text() = concat(&quot;Watson&quot; , &quot;'&quot; , &quot;s User Role &amp; Access&quot;) or . = concat(&quot;Watson&quot; , &quot;'&quot; , &quot;s User Role &amp; Access&quot;))]</value>
      <webElementGuid>2ee7dfba-c41d-44c1-995c-5450de81ea8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
