<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_WATSONS COMMAND CENTER_login</name>
   <tag></tag>
   <elementGuidId>60f2f9c2-634d-427a-b03d-3b70a0d81264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b3c35ca-adb5-4e53-b48d-3c50e103567a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton','WebPatterns_wtLayout_Login$block$wtAction$wtLoginButton','','__OSVSTATE,',''); return false;</value>
      <webElementGuid>67611564-7592-4020-a2a1-b97cb97e8747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ebf8a1e7-f3cc-4040-8c4f-c13bfa44313e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WebPatterns_wtLayout_Login$block$wtAction$wtLoginButton</value>
      <webElementGuid>869d1540-0dc7-444f-904d-d4e10570b843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>922162db-d3f8-44d2-8305-d45fe7b6c889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton</value>
      <webElementGuid>5a2833d5-ba2e-4117-9690-6ba4b0a831e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fc79369b-722c-4d11-929a-197aa4b2c992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Is_Default OSFillParent</value>
      <webElementGuid>1da58a17-fa3d-4f00-a9e2-df284bc1fb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton&quot;)</value>
      <webElementGuid>35965001-1445-481a-8445-037c09896983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton']</value>
      <webElementGuid>6f24374e-a8ef-4983-857f-dfc4d4a13937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WebPatterns_wtLayout_Login_block_wtAction']/input</value>
      <webElementGuid>96f28be2-a6b0-477c-b4d4-5fab52fd1d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>8ff830c5-2177-4202-ab8c-d97da163fe5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'WebPatterns_wtLayout_Login$block$wtAction$wtLoginButton' and @id = 'WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton']</value>
      <webElementGuid>b942c6ec-1386-4c6b-8ce6-8e4ef46c0072</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
