<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorMsg_Invalid access. User does not exist</name>
   <tag></tag>
   <elementGuidId>409a1e5c-a46b-466d-8d47-04b9b044370f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.feedback-message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feedbackMessageContainer']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>425e0072-684f-4b62-b9e1-6d9819d5aa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedback-message-text</value>
      <webElementGuid>f4e5fd69-e4f0-4ad3-b235-b80954912f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid access. User does not exist.</value>
      <webElementGuid>346b08dc-942e-4c5c-9ff5-0881dde88f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feedbackMessageContainer&quot;)/div[@class=&quot;feedback-message feedback-message-error&quot;]/div[@class=&quot;feedback-message-text&quot;]</value>
      <webElementGuid>bf93bb18-8de6-4f07-8afe-20acd66a2439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedbackMessageContainer']/div/div</value>
      <webElementGuid>f48831cd-3a2f-4e07-aa65-da863d9820e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Trade Vendor Portal'])[1]/preceding::div[1]</value>
      <webElementGuid>25a10595-1919-421c-8c55-5d788133a4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[1]/preceding::div[2]</value>
      <webElementGuid>41bc5e99-6234-4c72-b19e-176b28a7012f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid access. User does not exist.']/parent::*</value>
      <webElementGuid>41c76321-f622-409a-957d-da0a3c96762c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>7bd2b161-d716-40c9-b722-dfabe80a1cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Invalid access. User does not exist.' or . = 'Invalid access. User does not exist.')]</value>
      <webElementGuid>af1deebc-23df-4fa7-bb5a-1f868041390d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
