<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorMsg_Invalid username or password</name>
   <tag></tag>
   <elementGuidId>94c88895-849a-4e0d-8dd7-8cc9145e7688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.feedback-message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feedbackMessageContainer']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b83d7a9-e052-45d3-b9d9-31aea36ea322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedback-message-text</value>
      <webElementGuid>07880b86-2418-4a65-9fad-8d3a0efd6490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid username or password.</value>
      <webElementGuid>f1853a2c-299a-4bc2-bb9a-5a5f097ee496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feedbackMessageContainer&quot;)/div[@class=&quot;feedback-message feedback-message-error&quot;]/div[@class=&quot;feedback-message-text&quot;]</value>
      <webElementGuid>f81d06c7-c2cc-44bf-8e93-a5351dc99b78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedbackMessageContainer']/div/div</value>
      <webElementGuid>aa155dce-b3a1-4762-8c31-7ae6ba14119a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Trade Vendor Portal'])[1]/preceding::div[1]</value>
      <webElementGuid>3fc41436-120b-4baf-9579-301ce9b7e259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[1]/preceding::div[2]</value>
      <webElementGuid>cf1e2e28-1cda-4817-bb59-a8bfd7ac0b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid username or password.']/parent::*</value>
      <webElementGuid>6c45817b-df88-4b8a-80d4-6e570beb7228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>6bf452ab-b639-4b0d-89eb-bf590fc568f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Invalid username or password.' or . = 'Invalid username or password.')]</value>
      <webElementGuid>fb89367c-0eb2-4e34-8bb0-5a15d40519f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
