<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WATSONS COMMAND CENTER_username</name>
   <tag></tag>
   <elementGuidId>0a6c4a27-c8d2-4f12-963e-0ca94c53e0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WebPatterns_wtLayout_Login_block_wtUsername_WebPatterns_wt10_block_wtInput_wtUserNameInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WebPatterns_wtLayout_Login_block_wtUsername_WebPatterns_wt10_block_wtInput_wtUserNameInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a75f0856-508b-44e1-bc6f-fe073ed53343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WebPatterns_wtLayout_Login$block$wtUsername$WebPatterns_wt10$block$wtInput$wtUserNameInput</value>
      <webElementGuid>b72e3fcf-2d21-438c-9c48-981532ef544d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29952066-3ffd-4dd0-b2fb-816b18857eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f3bbf6ca-15e3-4c98-96a8-51e0b1b788cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WebPatterns_wtLayout_Login_block_wtUsername_WebPatterns_wt10_block_wtInput_wtUserNameInput</value>
      <webElementGuid>b727a0ac-3bb6-474f-8764-6043677e0f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7f22d06e-7526-4f5e-b88d-502996dfa010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent Mandatory</value>
      <webElementGuid>dad4c4e2-16b5-41d1-86be-a7534d6b7200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>03142d1f-d6a5-4d8f-86de-e0f3079fd28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton', arguments[0] || window.event);</value>
      <webElementGuid>51403b2d-d25a-4f44-8363-5ac5e77bccd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c2d1bc6-2290-4786-afb7-56613463a8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>37720acd-5ec6-4629-bdcb-f3dc79276d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>AppendEmail();</value>
      <webElementGuid>bbdb28fe-d4a1-4b91-860a-9b52408788ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WebPatterns_wtLayout_Login_block_wtUsername_WebPatterns_wt10_block_wtInput_wtUserNameInput&quot;)</value>
      <webElementGuid>b679bb95-39fc-4e58-9137-a16ff7ab55dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WebPatterns_wtLayout_Login_block_wtUsername_WebPatterns_wt10_block_wtInput_wtUserNameInput']</value>
      <webElementGuid>2480490c-b298-4277-ac12-17f254a3bb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='WebPatterns_wtLayout_Login_block_wtUsername_WebPatterns_wt10_block_wtInput_wtUserNameInputAjaxRfrsh']/input</value>
      <webElementGuid>2f3e9051-18ce-4df0-b782-14dd86376fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>eb71b7cc-387b-4051-a8f9-34cf02d272a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'WebPatterns_wtLayout_Login$block$wtUsername$WebPatterns_wt10$block$wtInput$wtUserNameInput' and @type = 'text' and @id = 'WebPatterns_wtLayout_Login_block_wtUsername_WebPatterns_wt10_block_wtInput_wtUserNameInput' and @placeholder = 'Username']</value>
      <webElementGuid>178b337b-27ad-4f97-9609-983c438bfb95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
