<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WATSONS COMMAND CENTER_password</name>
   <tag></tag>
   <elementGuidId>3ca3c03e-5db2-4c84-8625-d151afefd150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de72f499-3538-4e28-8172-86f3051ad698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WebPatterns_wtLayout_Login$block$wtPassword$WebPatterns_wt21$block$wtInput$wtPasswordInput</value>
      <webElementGuid>4fc4d223-fc77-4103-9230-bff3144a59ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>748151c0-b8bd-4646-92da-147f3ed4d89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput</value>
      <webElementGuid>d5164fbc-ec23-4e3f-989a-bbdf6e5e2b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0978b4b3-c054-4c68-afa9-2457a120250c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent Mandatory</value>
      <webElementGuid>5b84c606-771c-4e8e-8877-53fc7fa7deac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('WebPatterns_wtLayout_Login_block_wtAction_wtLoginButton', arguments[0] || window.event);</value>
      <webElementGuid>0a8ce34a-0396-44d1-9242-8f6282fbe2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7208c2b-a0a9-4295-ad45-57524a405acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d105029-1967-495a-814f-ccd86915db25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>4faf41d5-37d9-4588-ac94-83fa6d61fab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput','WebPatterns_wtLayout_Login$block$wtPassword$WebPatterns_wt21$block$wtInput$wtPasswordInput','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
      <webElementGuid>b1c9d09e-4c7b-4ac3-a4c0-309a0b427859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput','WebPatterns_wtLayout_Login$block$wtPassword$WebPatterns_wt21$block$wtInput$wtPasswordInput','Change','__OSVSTATE,',0);</value>
      <webElementGuid>fe2ebc15-961d-4096-afe8-2b9e2f0a5ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput&quot;)</value>
      <webElementGuid>d828f4f5-ec17-4b9c-9471-982e7bc0e5ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput']</value>
      <webElementGuid>fe436cd7-aa1e-4d8b-8646-e5e1d50d0233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInputAjaxRfrsh']/input</value>
      <webElementGuid>4004260a-a9b1-45a1-9f28-3dca64e7bf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>c90dda07-aa98-4b43-b356-99002f0d2910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'WebPatterns_wtLayout_Login$block$wtPassword$WebPatterns_wt21$block$wtInput$wtPasswordInput' and @type = 'password' and @id = 'WebPatterns_wtLayout_Login_block_wtPassword_WebPatterns_wt21_block_wtInput_wtPasswordInput' and @placeholder = 'Password']</value>
      <webElementGuid>f31c4678-a4a1-4971-8183-9cb5a112cc50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
