<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adminMenu_Watsons Command Center</name>
   <tag></tag>
   <elementGuidId>82bfd43c-4e95-4652-98d5-2b60e27ac527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-neutral-0.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;b13-PageLinks&quot;]/a[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49782fe9-9ce7-453f-b31f-8d7e71e982e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-neutral-0 font-bold</value>
      <webElementGuid>d49293cd-85ec-453d-adb4-7296e2350617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watsons Command Center</value>
      <webElementGuid>e4d30f6e-fc40-47d3-a3d7-f3e9bc0c3673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-PageLinks&quot;)/a[@class=&quot;padding-x-base padding-y-s margin-x-xs&quot;]/span[@class=&quot;text-neutral-0 font-bold&quot;]</value>
      <webElementGuid>99daed2b-2851-489f-a9dd-7f56c14dddba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b12-PageLinks']/a/span</value>
      <webElementGuid>154078b7-8526-480a-a809-e5ccf11bfed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::span[1]</value>
      <webElementGuid>8aa02cef-98a7-45d3-a21c-9be976c6bf7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watsons User'])[2]/preceding::span[2]</value>
      <webElementGuid>96c6b70f-5436-47f8-8775-2f4f73fc59ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Watsons Command Center']/parent::*</value>
      <webElementGuid>50cd13c3-2fc2-411f-810b-ba72ee50658f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>0c2ad71b-2a3a-4e05-9484-c3453772dd00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Watsons Command Center' or . = 'Watsons Command Center')]</value>
      <webElementGuid>da8e06ef-a382-49cc-87e3-543579382422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
