<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>APcontainerLabel_Non-Trade Vendor Portal</name>
   <tag></tag>
   <elementGuidId>7f039baa-8b82-4a15-a367-eb188a24467b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_wtMainContent_wtList_Applications_ctl02_wtExpression_ApplicationName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_wtMainContent_wtList_Applications_ctl02_wtExpression_ApplicationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d85ee61d-351f-4847-8eb2-ece7c67e39d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_wtMainContent_wtList_Applications_ctl02_wtExpression_ApplicationName</value>
      <webElementGuid>304d3704-4df6-470a-a7b9-620b8cca2eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non-Trade Vendor Portal</value>
      <webElementGuid>130b2f18-167e-4da6-a42e-e5f8e3ee7b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_wtMainContent_wtList_Applications_ctl02_wtExpression_ApplicationName&quot;)</value>
      <webElementGuid>68b72f22-191f-46f8-8e55-c0419d6245b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_wtMainContent_wtList_Applications_ctl02_wtExpression_ApplicationName']</value>
      <webElementGuid>b98a86d9-3c1a-47d8-8536-3d49d71c25ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_wtMainContent_wtList_Applications_ctl02_wt13']/div/div[2]/span</value>
      <webElementGuid>6ca4d232-8252-4bca-9b81-a07539c80cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watsons Teamwork+'])[1]/following::span[1]</value>
      <webElementGuid>fce32932-5da1-4dd3-b688-a4fda9ea33bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Application to access'])[1]/following::span[3]</value>
      <webElementGuid>fe9e5876-0b3d-4649-92f3-dd3453fcade8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Non-Trade Vendor Portal']/parent::*</value>
      <webElementGuid>9dfc81e0-393e-48aa-b898-6a27f78fd412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div[2]/span</value>
      <webElementGuid>4d21b8b2-c7a7-4685-9d31-beb307e17015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_wtMainContent_wtList_Applications_ctl02_wtExpression_ApplicationName' and (text() = 'Non-Trade Vendor Portal' or . = 'Non-Trade Vendor Portal')]</value>
      <webElementGuid>25f4842c-02cc-47cf-abcd-da260fb37221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
