<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titlePage_WATSONS COMMAND CENTER</name>
   <tag></tag>
   <elementGuidId>1c922659-5a25-4c47-a884-bc480916f735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LiverpoolTheme_wt20_block_wtHeader_WatsonsStyle_wt28_block_wt2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LiverpoolTheme_wt20_block_wtHeader_WatsonsStyle_wt28_block_wt2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8725de9b-54e1-4540-8b5a-bc49bbaa1da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiverpoolTheme_wt20_block_wtHeader_WatsonsStyle_wt28_block_wt2</value>
      <webElementGuid>8f00a397-406b-48ae-8f8c-8df66f41a3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>df1c30e1-5857-4d47-872d-8eff6e992d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/WatsonsStyle/</value>
      <webElementGuid>9d62234e-fd62-4c6a-b576-ec5ea8889bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WATSONS COMMAND CENTER</value>
      <webElementGuid>17b958cd-cdb9-4924-8ee8-4abf1c0a540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiverpoolTheme_wt20_block_wtHeader_WatsonsStyle_wt28_block_wt2&quot;)</value>
      <webElementGuid>d812f60d-b4a8-44e1-8ff2-8a4cf8d95490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LiverpoolTheme_wt20_block_wtHeader_WatsonsStyle_wt28_block_wt2']</value>
      <webElementGuid>a249cf7a-5508-4aa7-a622-26e7f6314102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LiverpoolTheme_wt20_block_wtHeader']/div[2]/a[2]</value>
      <webElementGuid>d32012cb-2f88-4463-87b8-c9cf56fc383d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WATSONS COMMAND CENTER')]</value>
      <webElementGuid>808c16bc-c721-45e2-b212-b72809d31dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/following::a[2]</value>
      <webElementGuid>df282f2d-c9b0-479b-9a7a-8462c7be6e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dave1 Gamab Col...'])[1]/following::a[3]</value>
      <webElementGuid>c3d5ed84-d042-42e8-bcb3-12221154b15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/preceding::a[1]</value>
      <webElementGuid>6620b144-55ab-442e-ab02-7221dfc75a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Tools'])[1]/preceding::a[2]</value>
      <webElementGuid>73e0c1c1-ff84-466e-b8d3-5f9e3b2f777d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WATSONS COMMAND CENTER']/parent::*</value>
      <webElementGuid>8d590225-9873-4e69-942c-a22e6cb3e352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/WatsonsStyle/')])[2]</value>
      <webElementGuid>de2a7c57-09f6-42e6-8193-41c0dde3e284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>cebfd40e-2d02-48ca-8d6d-fad11d3ee044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'LiverpoolTheme_wt20_block_wtHeader_WatsonsStyle_wt28_block_wt2' and @href = '/WatsonsStyle/' and (text() = 'WATSONS COMMAND CENTER' or . = 'WATSONS COMMAND CENTER')]</value>
      <webElementGuid>b1837a91-ad2a-43b4-8285-363c4c705276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
