<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleHeader_Select Application to access</name>
   <tag></tag>
   <elementGuidId>743e008b-e053-40ab-9129-6ba8ca87a858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_WebPatterns_wt2_block_wtColumn1_wtTitleOrContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_WebPatterns_wt2_block_wtColumn1_wtTitleOrContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b3c9260-aaff-4ec6-b43f-95707f805e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_WebPatterns_wt2_block_wtColumn1_wtTitleOrContent</value>
      <webElementGuid>f40b8e1b-ee28-4cd4-be92-d865d334def5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>this-cont</value>
      <webElementGuid>fa74475d-038d-497b-bcad-e7f8675fe187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>b614be29-bd60-4328-a238-9c024cfaa983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Application to access</value>
      <webElementGuid>1f74db4d-cd03-47e3-809c-389a7b625f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_WebPatterns_wt2_block_wtColumn1_wtTitleOrContent&quot;)</value>
      <webElementGuid>57c68d98-1527-4318-8a5e-da4502f29743</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_WebPatterns_wt2_block_wtColumn1_wtTitleOrContent']</value>
      <webElementGuid>48815ec1-85fe-4d0e-a600-fe35b21787cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_WebPatterns_wt2_block_wtColumn1']/div/div</value>
      <webElementGuid>3ec6f683-adfd-47a3-91d8-1e2a68d298d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::div[15]</value>
      <webElementGuid>2daa9994-3ddf-426a-b357-cfb0d1a0d138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating Unit'])[1]/following::div[18]</value>
      <webElementGuid>b530dfd7-f6b9-4c97-86c0-d8ae90e82dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watsons Career Website'])[1]/preceding::div[9]</value>
      <webElementGuid>65354df2-6de2-43ff-9230-8a0ee59dc46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watsons PPA'])[1]/preceding::div[13]</value>
      <webElementGuid>f0729ba7-1724-43b4-8a91-6983c9eeedc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Application to access']/parent::*</value>
      <webElementGuid>970f1426-a732-4d26-8f03-f24dc8025cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>a027c39b-d880-4846-bd58-0d821a666a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'LiverpoolTheme_wt20_block_wtMainContent_WatsonsStyle_wtBlock_Applications_block_WebPatterns_wt2_block_wtColumn1_wtTitleOrContent' and (text() = 'Select Application to access' or . = 'Select Application to access')]</value>
      <webElementGuid>9f3604fa-5782-4ee6-940d-c1f6f909e113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
