<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_Icon</name>
   <tag></tag>
   <elementGuidId>7307024f-ab4c-427f-b3a5-cf7c6b9974a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.text-neutral-0.fa.fa-times.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/div/div/div[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>952b858d-95b5-4266-954f-b77f1e9932f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon text-neutral-0 fa fa-times fa-1x</value>
      <webElementGuid>9cc6d48f-d615-425f-b95b-4aa595401769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RAPopUp&quot;)/div[@class=&quot;popup-content&quot;]/div[@class=&quot;padding-s&quot;]/div[@class=&quot;text-neutral-0 text-align-right  ThemeGrid_Width6 ThemeGrid_MarginGutter&quot;]/a[@class=&quot;text-neutral-0 margin-right-s&quot;]/i[@class=&quot;icon text-neutral-0 fa fa-times fa-1x&quot;]</value>
      <webElementGuid>60a7e935-272b-4329-8637-91e306e9bf92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RAPopUp']/div/div/div[2]/a/i</value>
      <webElementGuid>93f53d21-94b0-4128-a768-cdf96add825a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/a/i</value>
      <webElementGuid>a97c75b1-c6c9-4b18-9ac7-df56e3c944a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
