<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>container_Tickets</name>
   <tag></tag>
   <elementGuidId>eabad126-05d4-49fe-8849-157a0ed5c0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContent']/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>640f266c-5a9b-4e1b-9966-b0598dcb0958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-y-base padding-x-xl card-style display-flex flex-direction-column justify-content-space-between</value>
      <webElementGuid>6fea9161-2b28-4908-ac60-09578c703693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;b1-MainContent&quot;]/div/div[4]</value>
      <webElementGuid>5f87705d-4e85-48e4-a77b-e018278d2b43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContent']/div/div[4]</value>
      <webElementGuid>0cee4fe5-a62d-4552-ac89-ad81dd0ae37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[3]/following::div[1]</value>
      <webElementGuid>bf08e486-b3db-472a-9873-6715c55a673f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulletin Memo'])[3]/following::div[2]</value>
      <webElementGuid>3280a7c5-0890-4dbd-ab96-0935391a65c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>9c684c0a-be50-448a-a464-2ca6923c24e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '12OpenTicketsView All' or . = '12OpenTicketsView All')]</value>
      <webElementGuid>2df414c0-8816-4204-8d32-729c02ca55dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
