<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>container_BulletinMemo</name>
   <tag></tag>
   <elementGuidId>645c9017-063b-4851-8153-b6ca52b4dce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContent']/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a30f7ac2-6986-442e-bc23-19e18a521d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-y-base padding-x-xl card-style display-flex flex-direction-column justify-content-space-between</value>
      <webElementGuid>2f6d3a51-3d3a-47bb-9c89-45d6ec39ad5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;b1-MainContent&quot;]/div/div[3]</value>
      <webElementGuid>d5d5b293-8161-4cc9-9a15-39a230e76055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContent']/div/div[3]</value>
      <webElementGuid>4655bd0e-823a-447a-89aa-17cc3ab6b7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[2]/following::div[1]</value>
      <webElementGuid>73f69743-cf2a-425a-adeb-bef8ce03fca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance Advice'])[2]/following::div[2]</value>
      <webElementGuid>ffd29929-6e6c-4aef-9404-6ba30170d719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]</value>
      <webElementGuid>162ee1ed-ee7b-4d36-a042-2f9501176481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1PublishedBulletin MemoView All' or . = '1PublishedBulletin MemoView All')]</value>
      <webElementGuid>934fe788-7f09-4f3f-a736-f97786df81d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
