<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>counter_UnreadBM</name>
   <tag></tag>
   <elementGuidId>5980d11c-018b-467c-baf6-6fd75c49bd55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-Column1']/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Column1 > div.padding-s > div > a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c38ceb94-1293-48d9-b986-8a448f9cdaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Column1&quot;)/div[@class=&quot;padding-s&quot;]/div[1]/a[1]/span[1]</value>
      <webElementGuid>67f56555-fcf2-49a8-b0db-f40df68ae01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Column1']/div/div/a/span</value>
      <webElementGuid>8a8f568c-95ba-4436-b8b1-0dcc80d696d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/following::span[1]</value>
      <webElementGuid>3c452550-2eb3-4b43-9f29-f987c30986e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance Advice'])[2]/following::span[2]</value>
      <webElementGuid>30a1fa4c-9ee4-4db0-8352-2a97577bf1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='unread'])[2]/preceding::span[1]</value>
      <webElementGuid>fe353c18-29ab-4713-99a0-f0a44124d2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulletin Memo'])[2]/preceding::span[2]</value>
      <webElementGuid>7dd093a4-a32e-45dc-9e0a-897e4121d320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='99']/parent::*</value>
      <webElementGuid>1e15d5b2-3429-4d47-aff3-917a33ca4d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/a/span</value>
      <webElementGuid>af5d337a-b51b-49b6-a21f-eec14600a420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '99' or . = '99')]</value>
      <webElementGuid>fd327ef3-73f9-4c39-8c17-024878b009e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
