<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>counter_UnreadTickets</name>
   <tag></tag>
   <elementGuidId>ca30cbb3-3da9-4efd-b85a-c42bb2fb2658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b8-Column1']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b8-Column1 > div.padding-s > div > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3984a6a7-45bb-4f4c-97c4-551a56c59a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b8-Column1&quot;)/div[@class=&quot;padding-s&quot;]/div[1]/span[1]</value>
      <webElementGuid>2bc48fe0-7f7c-4baf-93fe-224a62d9638f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-Column1']/div/div/span</value>
      <webElementGuid>5a05f8ca-569d-4670-b298-dfd7bfb1b65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[3]/following::span[1]</value>
      <webElementGuid>1dac5a2e-ee72-42d3-a17b-0c218cd60f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form 2307'])[2]/following::span[2]</value>
      <webElementGuid>f044faac-39a4-4ce2-9a62-d9059dbca88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='unread'])[4]/preceding::span[1]</value>
      <webElementGuid>454b61f4-9022-4223-a326-f2670f83db7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tickets'])[1]/preceding::span[2]</value>
      <webElementGuid>e02f4ce6-3c63-4caa-8a0a-4244367fb573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>bcd0e0d0-116a-4366-ba68-a9feae8493ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>9d0c9ac5-ebbc-4d8a-8187-1cc9f8792893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0' or . = '0')]</value>
      <webElementGuid>55fb8df5-91f4-4b04-8ef1-88a14abbc175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
