<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Form2307</name>
   <tag></tag>
   <elementGuidId>bc1712b2-dfd5-4161-aec6-c83b86b058c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.report-img-size</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContent']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4e22cb7-8e4c-4387-a162-efaddef28063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-img-size</value>
      <webElementGuid>8f6e8147-9d92-4b3f-8679-b3a2c9056878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NonTradeVendorPortal/img/NonTradeVendorPortal.Group36Form_2307.svg?ysj_4+UaVRdoj+gYh8Y2rg</value>
      <webElementGuid>4c89ce63-3cc9-4ccd-a8ab-b59f2a206a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-MainContent&quot;)/div[@class=&quot;display-flex column-gap-base&quot;]/div[@class=&quot;card-style display-flex flex-direction-column justify-content-space-between&quot;]/div[@class=&quot;position-relative display-flex flex-direction-column justify-content-space-between row-gap-xs report-img-size&quot;]/img[@class=&quot;report-img-size&quot;]</value>
      <webElementGuid>8e8d9577-bd49-4c93-b67a-be743d6de047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContent']/div/div/div/img</value>
      <webElementGuid>95568bee-1590-4b3b-9f00-2e22278bdeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>324e2f7a-5644-4f9c-9ef9-89cb0fce5c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/NonTradeVendorPortal/img/NonTradeVendorPortal.Group36Form_2307.svg?ysj_4+UaVRdoj+gYh8Y2rg']</value>
      <webElementGuid>3ecb7f1b-c68d-410c-8653-bce98fd2c1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
