<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Tickets</name>
   <tag></tag>
   <elementGuidId>4083d2bf-652c-46d0-8877-0275a88789a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-align-center.position-relative > img.report-img-size</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContent']/div/div[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c419ea20-2f38-48ac-805b-d401ebec5120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-img-size</value>
      <webElementGuid>2b1d7ace-bb25-4bc0-9d48-4a507ce76292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NonTradeVendorPortal/img/NonTradeVendorPortal.Group35ticket.svg?EstnhOCrpovxt4luvO9pfA</value>
      <webElementGuid>a0abd92b-04a6-4f6c-bdc6-ffa7246eaeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-MainContent&quot;)/div[@class=&quot;display-flex column-gap-base&quot;]/div[@class=&quot;padding-y-base padding-x-xl card-style display-flex flex-direction-column justify-content-space-between&quot;]/div[@class=&quot;position-relative display-flex flex-direction-column justify-content-space-between row-gap-xs&quot;]/div[@class=&quot;text-align-center position-relative&quot;]/img[@class=&quot;report-img-size&quot;]</value>
      <webElementGuid>31dd381b-a0fa-44b6-b764-10f7ef426fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContent']/div/div[4]/div/div/img</value>
      <webElementGuid>81c92a36-ef9a-4e84-8d12-faf861766aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/img</value>
      <webElementGuid>4ec88c86-20e0-4063-8f11-0d379fbc9a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/NonTradeVendorPortal/img/NonTradeVendorPortal.Group35ticket.svg?EstnhOCrpovxt4luvO9pfA']</value>
      <webElementGuid>eeb79a91-8f83-4c58-94d5-4c3dbd95c350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
