<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Bulletin Memo</name>
   <tag></tag>
   <elementGuidId>72919544-908b-47cc-90cc-b129cb33850a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContent']/div/div[3]/div/div[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>159ef708-12ef-4038-8b52-d13c8fdfee76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
      <webElementGuid>48c20a7d-70c0-4a1d-8a85-3b81a2d7e71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulletin Memo</value>
      <webElementGuid>ab45c9dc-d375-43ea-8b70-1f50d1b70b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-MainContent&quot;)/div[@class=&quot;display-flex column-gap-base&quot;]/div[@class=&quot;padding-y-base padding-x-xl card-style display-flex flex-direction-column justify-content-space-between&quot;]/div[@class=&quot;position-relative display-flex flex-direction-column justify-content-space-between row-gap-xs report-img-size&quot;]/div[@class=&quot;display-flex flex-direction-column text-align-center&quot;]/span[@class=&quot;OSFillParent&quot;]</value>
      <webElementGuid>b54888dd-2af9-42ff-a011-2eb2dea36526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContent']/div/div[3]/div/div[2]/span[2]</value>
      <webElementGuid>051dda0e-e2cc-4943-94f8-1216d11b2813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[1]/following::span[1]</value>
      <webElementGuid>c7b15bbe-f848-42a1-b552-7efa30f228ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[2]/following::span[3]</value>
      <webElementGuid>22c45229-ab22-4567-a082-16b944abfefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[3]/preceding::span[1]</value>
      <webElementGuid>c7378e6f-72c6-4851-9d51-77fd00c9de45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::span[2]</value>
      <webElementGuid>0d37b060-1ce0-41a4-af58-04bb29e4ba9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/span[2]</value>
      <webElementGuid>a7024e99-5a53-44ab-8644-933be6d05c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bulletin Memo' or . = 'Bulletin Memo')]</value>
      <webElementGuid>e2bc459e-4302-47fa-b035-6782f3756972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
