<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_UnreadRA</name>
   <tag></tag>
   <elementGuidId>eddf725c-4162-4628-9ec2-57c0de67c480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.padding-y-base.padding-x-xl.card-style.display-flex.flex-direction-column.justify-content-space-between > div.position-relative.display-flex.flex-direction-column.justify-content-space-between.row-gap-xs.report-img-size > div.display-flex.flex-direction-column.text-align-center > span.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContent']/div/div[2]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>558892ba-270c-4465-8c5d-827e48c1619b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-bold</value>
      <webElementGuid>0f8f8b27-1619-4b72-9943-d76d40518c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unread</value>
      <webElementGuid>e9d0e79f-4776-4733-b376-e46c7bdfcb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-MainContent&quot;)/div[@class=&quot;display-flex column-gap-base&quot;]/div[@class=&quot;padding-y-base padding-x-xl card-style display-flex flex-direction-column justify-content-space-between&quot;]/div[@class=&quot;position-relative display-flex flex-direction-column justify-content-space-between row-gap-xs report-img-size&quot;]/div[@class=&quot;display-flex flex-direction-column text-align-center&quot;]/span[@class=&quot;font-bold&quot;]</value>
      <webElementGuid>a3b55751-9287-47e1-9f29-f54de918bb43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContent']/div/div[2]/div/div[2]/span</value>
      <webElementGuid>da900dab-446e-4fc6-bee7-110a681556e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/following::span[2]</value>
      <webElementGuid>3be7f7a8-655c-4327-9dd9-e2394d7febf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form 2307'])[2]/following::span[2]</value>
      <webElementGuid>63f95af9-1966-487c-8746-0ce200244ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance Advice'])[2]/preceding::span[1]</value>
      <webElementGuid>59bb3879-61df-4a04-930d-f7706bab6f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[2]/preceding::span[2]</value>
      <webElementGuid>a629710a-bec1-4362-8065-c561dc6370c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>54e276de-cd53-4fd9-a17f-cb141aec407b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Unread' or . = 'Unread')]</value>
      <webElementGuid>e95d778e-6484-4a86-9abb-d3358ff727eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
