<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Audit Trail_SP</name>
   <tag></tag>
   <elementGuidId>618c6fe3-3c4d-40b4-b1e1-aa3c3b8fac2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-PageLinks']/a[3]/span
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;b12-PageLinks&quot;]/a/span[count(. | //span[@class = 'text-neutral-0 font-bold' and (text() = 'Audit Trail' or . = 'Audit Trail')]) = count(//span[@class = 'text-neutral-0 font-bold' and (text() = 'Audit Trail' or . = 'Audit Trail')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91febcf7-a76d-43f9-8b0e-6179772f54fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-neutral-0 font-bold</value>
      <webElementGuid>4259da0a-b0c7-46fb-960b-58b0f410fe2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Audit Trail</value>
      <webElementGuid>a1524e3f-eab6-4ece-bd9c-b6196880a3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;b12-PageLinks&quot;]/a/span</value>
      <webElementGuid>55d033ef-71bd-4af2-840b-a369b238217a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/a[3]/span</value>
      <webElementGuid>915b65df-27d7-4151-89c8-c3724a9c7b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::span[1]</value>
      <webElementGuid>3d718fd3-9180-499d-8164-c44005904ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor User'])[1]/following::span[2]</value>
      <webElementGuid>893957bf-15ae-47fd-ae76-238b1f5e0021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESI Admin'])[1]/preceding::span[1]</value>
      <webElementGuid>d2732496-0c67-4292-8a4a-af5d44edc2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::span[2]</value>
      <webElementGuid>851d03c1-e287-4b22-86d2-5e1c60d87b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Audit Trail']/parent::*</value>
      <webElementGuid>ba40643a-ddc4-4216-8c8e-eab0f1ba93a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>d7450faf-5d93-4b30-b239-923f9e303e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Audit Trail' or . = 'Audit Trail')]</value>
      <webElementGuid>661d6b1a-c053-4064-9a42-0085b00282ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
