<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popupLabel_Remittance Advice</name>
   <tag></tag>
   <elementGuidId>b9fad56b-2fce-412e-ada3-8c4b4e7065fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RAPopUp']/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ThemeGrid_Width7 > span.margin-left-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73cea088-39af-4fce-ae5e-a28cad0d63d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-left-s</value>
      <webElementGuid>ee9b31d7-14e9-4e0d-bdc3-2a3719de8b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remittance Advice</value>
      <webElementGuid>6031cc49-88de-4aad-bf43-e0c1abe0af28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RAPopUp&quot;)/div[@class=&quot;popup-content&quot;]/div[@class=&quot;padding-s&quot;]/div[@class=&quot;padding-s&quot;]/div[@class=&quot;ThemeGrid_Width7&quot;]/span[@class=&quot;margin-left-s&quot;]</value>
      <webElementGuid>88f54098-9f5b-49e2-8d00-e719d4fea1de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RAPopUp']/div/div/div/div/span</value>
      <webElementGuid>7fe09a49-c1b4-48d2-ba66-1d092c71057b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[1]</value>
      <webElementGuid>4ca15242-5d59-4b32-82c5-3107e64dfc98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::span[1]</value>
      <webElementGuid>52179bf2-eb59-4aa3-bfac-e48bc826a83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RA1064400_0074303.pdf'])[1]/preceding::span[2]</value>
      <webElementGuid>d848dcce-6218-49da-a529-3182832edd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RA1064400_0074303.xlsx'])[1]/preceding::span[4]</value>
      <webElementGuid>e6049c3c-5ae4-4dcc-94f4-97f10c3ef189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/span</value>
      <webElementGuid>62bac5a8-fe05-45d5-ac7c-a33005647c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Remittance Advice' or . = 'Remittance Advice')]</value>
      <webElementGuid>aec8f367-a866-4a3d-815c-6896a39eaa04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
