<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popupLabel_Form 2307</name>
   <tag></tag>
   <elementGuidId>8c1706b3-6668-49ac-858d-0bca0da34099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Form2307Pop']/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ThemeGrid_Width7 > span.margin-left-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>53423cd1-2e1e-402b-8d75-381b47d9f1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-left-s</value>
      <webElementGuid>ac4f450e-3271-4cb0-a348-8858cdd4e68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form 2307</value>
      <webElementGuid>22ba84e8-7fca-4092-b846-5d8b2e0fae96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form2307Pop&quot;)/div[@class=&quot;popup-content&quot;]/div[@class=&quot;padding-s&quot;]/div[@class=&quot;padding-s&quot;]/div[@class=&quot;ThemeGrid_Width7&quot;]/span[@class=&quot;margin-left-s&quot;]</value>
      <webElementGuid>491a2e02-c39f-43c4-85b0-95fd46c513a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Form2307Pop']/div/div/div/div/span</value>
      <webElementGuid>5ee3e31d-c662-4b90-a044-325b7ae26ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[1]</value>
      <webElementGuid>c65f852c-2854-486c-a361-5fcfd8c3e753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::span[1]</value>
      <webElementGuid>f80a54cb-4728-4702-a623-a4e567a2c795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/span</value>
      <webElementGuid>b5d15b19-8ccc-4982-846b-e160d5db5f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Form 2307' or . = 'Form 2307')]</value>
      <webElementGuid>539cdc51-63b2-4ca4-857a-52cd7038d74b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
