<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subMenu_Remittance Advice</name>
   <tag></tag>
   <elementGuidId>50f62072-09d8-4618-b2d9-bb1083590674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b2-Items']/a[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > span.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c14a3d4e-3c01-4bff-b2fb-6e41b3905c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary</value>
      <webElementGuid>bfdcf6ae-1fb1-4651-a149-c79a12869ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remittance Advice</value>
      <webElementGuid>5cd883d2-3f5b-4abc-bb91-6f2060eb0c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b2-Items&quot;)/a[2]/span[@class=&quot;text-primary&quot;]</value>
      <webElementGuid>138250db-cb7f-4225-8d43-37720740fa3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-Items']/a[2]/span</value>
      <webElementGuid>bc515fd8-4cd2-46e8-96f2-e54ccecdfcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form 2307'])[1]/following::span[1]</value>
      <webElementGuid>ef44f2c9-dc9e-495c-805e-41bc441d8370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/following::span[2]</value>
      <webElementGuid>fbc2f15a-7af2-4074-b971-9a8baa1aed6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulletin Memo'])[1]/preceding::span[1]</value>
      <webElementGuid>5257bb03-af85-4b3f-a8ab-a4200cbf9fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOHL INDUSTRIES CORPORATION'])[1]/preceding::span[2]</value>
      <webElementGuid>ef8d0c35-00fa-43e1-9de4-bcd5196b0987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remittance Advice']/parent::*</value>
      <webElementGuid>25bd9abf-2076-4c6d-a33a-df17dd6b2c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>894f90a1-04e6-4954-aa84-7ba3e1f002bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Remittance Advice' or . = 'Remittance Advice')]</value>
      <webElementGuid>f4205731-5e86-439c-b230-a11ae6e0d154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
