<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tileIconForm2307_Inbox</name>
   <tag></tag>
   <elementGuidId>9abd14df-4ddf-415e-8b56-a1a02d516c60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b7-Column2 > div.margin-top-m > i.icon.fa.fa-envelope-o.fa-4x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b7-Column2']/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ad932510-cc3c-4801-8f8a-010afccd0463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-envelope-o fa-4x</value>
      <webElementGuid>9ea3092d-9be6-4f1e-a39d-c7cce8f55a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-Column2&quot;)/div[@class=&quot;margin-top-m&quot;]/i[@class=&quot;icon fa fa-envelope-o fa-4x&quot;]</value>
      <webElementGuid>96542e1f-032b-49be-822f-d57d0723dedc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-Column2']/div/i</value>
      <webElementGuid>6de1b1e7-0dcd-46f8-bf76-2101a7493b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/i</value>
      <webElementGuid>1f78a824-f0be-48f0-b411-3aecd8af9d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
