<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tileLabel_Remittance Advice</name>
   <tag></tag>
   <elementGuidId>50f62072-09d8-4618-b2d9-bb1083590674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b4-Column1&quot;)/div[@class=&quot;padding-s&quot;]/div[2]/span[1][count(. | //span[(text() = 'Remittance Advice' or . = 'Remittance Advice')]) = count(//span[(text() = 'Remittance Advice' or . = 'Remittance Advice')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-Column1']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64366f1a-8fd2-4c10-b3ab-f77d7f35cb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remittance Advice</value>
      <webElementGuid>3f0550ab-9f39-43a2-b554-1e216674ff83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-Column1&quot;)/div[@class=&quot;padding-s&quot;]/div[2]/span[1]</value>
      <webElementGuid>2c9524cc-b8a1-4d3c-962e-58c06e1bdafd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-Column1']/div/div[2]/span</value>
      <webElementGuid>72d965d9-fa56-4865-93d4-1adbcea221dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='unread'])[1]/following::span[1]</value>
      <webElementGuid>23f54dbc-1d50-40e8-acb1-d8ffafbbb707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[3]</value>
      <webElementGuid>a9fef866-db3c-4c17-8e0e-32a56b7bb30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::span[1]</value>
      <webElementGuid>31ad672a-d869-49d1-aa7d-cfd067fe770e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='unread'])[2]/preceding::span[3]</value>
      <webElementGuid>8a1d402f-3362-4211-91f4-f21c74ad626c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>0c611c24-3d23-456e-b9eb-cdceb1c3b26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Remittance Advice' or . = 'Remittance Advice')]</value>
      <webElementGuid>c9e0e7b6-64d8-455c-b272-ce6f9bd59c7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
