<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tileIconBM_Inbox</name>
   <tag></tag>
   <elementGuidId>96d58424-c9f5-40de-88eb-fb2f4a59764d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-Column2 > div.margin-top-m > i.icon.fa.fa-envelope-o.fa-4x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-Column2']/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>225c513b-f01a-4fff-8997-76d66029f1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-envelope-o fa-4x</value>
      <webElementGuid>be925408-7fef-4db6-b07a-58823231cfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Column2&quot;)/div[@class=&quot;margin-top-m&quot;]/i[@class=&quot;icon fa fa-envelope-o fa-4x&quot;]</value>
      <webElementGuid>dd93330d-fa6b-4c0e-8e30-639df50a75b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Column2']/div/i</value>
      <webElementGuid>50feb2c8-671f-43ec-90ef-b661b3deeee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/i</value>
      <webElementGuid>23108ef3-cb32-458b-8378-72b83cff8270</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
