<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tileLabel_BulletinMemo</name>
   <tag></tag>
   <elementGuidId>5c55b300-d3a2-4494-89ef-7e1244e4504d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-Column1']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5bdecdbd-8ed6-4665-934c-8924dff758ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulletin Memo</value>
      <webElementGuid>be7dd159-1fb5-47c7-8101-52cd749621b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Column1&quot;)/div[@class=&quot;padding-s&quot;]/div[2]/span[1]</value>
      <webElementGuid>c7bbc5a2-12bc-44f8-b5c4-3428a6c0d307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Column1']/div/div[2]/span</value>
      <webElementGuid>0b68de4a-50c8-4258-bc3b-4a3970c24460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='unread'])[2]/following::span[1]</value>
      <webElementGuid>40119d12-829e-4a33-8111-0985e2f8cada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/following::span[3]</value>
      <webElementGuid>c5514546-7d2c-43e4-ac07-974f56b797c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[2]/preceding::span[1]</value>
      <webElementGuid>10ebbca3-e467-491f-bb5e-6443611bea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='unread'])[3]/preceding::span[3]</value>
      <webElementGuid>c13f7f22-4fa6-4a8c-a5b0-9f615276f7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/span</value>
      <webElementGuid>ac33d981-3855-46c7-bcd7-5c92c819139c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bulletin Memo' or . = 'Bulletin Memo')]</value>
      <webElementGuid>94aa550a-b2f6-497f-a5d3-5fc7308e46a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
