<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tile_RemittanceAdvice</name>
   <tag></tag>
   <elementGuidId>4c2900f5-1d0d-4393-86f4-a630b1e0495e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.padding-s.ThemeGrid_Width10</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b3-Column1&quot;)/div[@class=&quot;padding-s ThemeGrid_Width10&quot;][count(. | //div[@class = 'padding-s ThemeGrid_Width10']) = count(//div[@class = 'padding-s ThemeGrid_Width10'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-Column1']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87831ae9-b055-4696-9d83-646044c37ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-s ThemeGrid_Width10</value>
      <webElementGuid>ab6d3661-55fc-4b7f-96ba-c182060f7c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-Column1&quot;)/div[@class=&quot;padding-s ThemeGrid_Width10&quot;]</value>
      <webElementGuid>4a1315f3-c10c-4bf1-9def-4ee17b13e897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-Column1']/div</value>
      <webElementGuid>3a0be622-181d-48ab-af7b-6ef9ed5ed33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[8]</value>
      <webElementGuid>504ced22-df88-495e-9a1e-271ae1e54a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[14]</value>
      <webElementGuid>e5cfe8d2-f6d9-424a-8daa-2694a884a14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>a2f3b4df-67f4-420d-9637-e2ce92598efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '8unreadRemittance AdviceView All' or . = '8unreadRemittance AdviceView All')]</value>
      <webElementGuid>6d67d8ff-faa7-41b7-a88e-f0427dd5984b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
