<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tileIconTickets_Inbox</name>
   <tag></tag>
   <elementGuidId>59b9dda7-2b5e-43cb-8945-d876f7d7f5ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b8-Column2 > div.margin-top-m > i.icon.fa.fa-envelope-o.fa-4x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b8-Column2']/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>261998a5-ef98-43e0-8b00-2c7550e7010f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-envelope-o fa-4x</value>
      <webElementGuid>f2ca224f-d73b-4aea-94a2-5bfa0ad9efbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b8-Column2&quot;)/div[@class=&quot;margin-top-m&quot;]/i[@class=&quot;icon fa fa-envelope-o fa-4x&quot;]</value>
      <webElementGuid>496c2bb1-64f7-4d29-a91b-45cddf20ca36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-Column2']/div/i</value>
      <webElementGuid>d8b40905-2d23-476d-bf81-5db22260ee44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div[2]/div/i</value>
      <webElementGuid>d3134185-5314-48ce-bc78-60ec9552f75b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
