<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invalidDesc_You dont have permissions to view the r_886a38</name>
   <tag></tag>
   <elementGuidId>a4c80eec-718e-463f-b31f-6905c88fc98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LiverpoolTheme_wt10_block_wtMainContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LiverpoolTheme_wt10_block_wtMainContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a5f73a5-2964-408b-af60-aaff631b2c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiverpoolTheme_wt10_block_wtMainContent</value>
      <webElementGuid>07ba7ee0-06f9-4a2c-bebd-5f8aa6ed39d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MainContent</value>
      <webElementGuid>aa4739c4-df9d-40e9-9edb-d695e145dbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You don't have permissions to view the required screen. Please contact the system administrator.</value>
      <webElementGuid>10beb42c-627d-4f6d-ad0d-565dd0b9f2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiverpoolTheme_wt10_block_wtMainContent&quot;)</value>
      <webElementGuid>792a8848-8953-412a-9935-75f5befa185f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='LiverpoolTheme_wt10_block_wtMainContent']</value>
      <webElementGuid>42502dd9-9088-45ee-abeb-151c58dbeebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='WebForm1']/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>dc86d7de-81ac-4ba7-b764-55288dcb162a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Permissions'])[2]/following::div[2]</value>
      <webElementGuid>dd776134-57c0-47e6-a785-3a26fb71b139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::div[8]</value>
      <webElementGuid>55e5ded2-7fec-4523-9225-05e3746d208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Development Resources'])[1]/preceding::div[1]</value>
      <webElementGuid>f7307df0-a8bf-4b8c-a6ca-22e3796309ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>2e87d949-9039-41a0-9f4c-25ebb39a1c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'LiverpoolTheme_wt10_block_wtMainContent' and (text() = concat(&quot;You don&quot; , &quot;'&quot; , &quot;t have permissions to view the required screen. Please contact the system administrator.&quot;) or . = concat(&quot;You don&quot; , &quot;'&quot; , &quot;t have permissions to view the required screen. Please contact the system administrator.&quot;))]</value>
      <webElementGuid>cf2008c5-dd6f-491a-818e-d81416d0953f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
